name: Create Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        cd app
        npm run ci-build
        cd ../worker
        npm run ci-build
        cd ..
        cp --recursive --parents index.html app/index.html app/favicon.ico app/images app/styles app/dist/browser/browser.js worker/worker.js worker/dist/browser/browser.js dist/web
    - uses: actions/upload-artifact@v2
      with:
        name: Web
        path: dist/web
    - uses: actions/upload-artifact@v2
      with:
        name: App Docs
        path: app/dist/docs
    - uses: actions/upload-artifact@v2
      with:
        name: Worker Docs
        path: worker/dist/docs
    - uses: actions/upload-artifact@v2
      with:
        name: Editor Docs
        path: worker/dist/editor-docs